# Generated by Django 4.1.1 on 2022-10-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_product_price_alter_profile_is_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizes',
            name='off_price',
        ),
        migrations.RemoveField(
            model_name='productsizes',
            name='price',
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Размер'),
        ),
    ]
