# Generated by Django 4.1.1 on 2022-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_remove_productsizes_off_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizes',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='productsizes',
            name='product',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='image6',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='clothes.productsizes'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image1',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение1'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение2'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image3',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение3'),
        ),
    ]
