# Generated by Django 4.1.1 on 2022-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_remove_product_size_productsizes_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizes',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='clothes.productsizes'),
        ),
    ]
