# Generated by Django 4.1.1 on 2022-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_remove_productsizes_product_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='О нас')),
                ('tel', models.CharField(max_length=30, verbose_name='телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
    ]
