# Generated by Django 4.1.1 on 2023-01-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_remove_productsizes_product_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
    ]
