# Generated by Django 4.1.1 on 2022-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_information_remove_product_size_delete_productsizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=30, verbose_name='телефон')),
                ('mail', models.CharField(max_length=50, verbose_name='почта')),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='information',
            name='tel',
        ),
    ]
