# Generated by Django 4.2 on 2023-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_profile_options_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение4'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение5'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image6',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение6'),
        ),
    ]
