# Generated by Django 4.1.1 on 2023-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_contacts_remove_information_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='five',
            field=models.BooleanField(default=False, verbose_name='48 размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='four',
            field=models.BooleanField(default=False, verbose_name='46 размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='three',
            field=models.BooleanField(default=False, verbose_name='44 размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='two',
            field=models.BooleanField(default=False, verbose_name='42 размер'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение4'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение5'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='image6',
            field=models.ImageField(blank=True, default='', upload_to='static/clothes/images/', verbose_name='Изображение6'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=models.CharField(max_length=303, verbose_name='телефон'),
        ),
    ]
